class CfgWorlds
{
    class GenericNames
    {
        class VietnameseMen
        {
            class FirstNames
            {
                An = "An";
                Bao = "Bao";
                Cuong = "Cuong";
                Dung = "Dung";
                Hai = "Hai";
                Khoa = "Khoa";
                Linh = "Linh";
                Minh = "Minh";
                Quang = "Quang";
                Tu = "Tu";
            };
            class LastNames
            {
                Nguyen = "Nguyen";
                Tran = "Tran";
                Le = "Le";
                Pham = "Pham";
                Hoang = "Hoang";
                Phan = "Phan";
                Vu = "Vu";
                Dang = "Dang";
                Bui = "Bui";
                Ngo = "Ngo";
                Duong = "Duong";
                Dinh = "Dinh";
                Ly = "Ly";
                Luu = "Luu";
                Thach = "Thach";
                Ton = "Ton";
                Tieu = "Tieu";
                Quach = "Quach";
                Diep = "Diep";
                Huynh = "Huynh";
                Trinh = "Trinh";
                Tu = "Tu";
                Gia = "Gia";
                Van = "Van";
                Luong = "Luong";
                Nghiem = "Nghiem";
                Khanh = "Khanh";
                Son = "Son";
                Dao = "Dao";
                Tam = "Tam";
                Hien = "Hien";
            };
        };
        class LaoMen
        {
            class FirstNames
            {
                Somchai = "Somchai";
                Bounthavy = "Bounthavy";
                Khamla = "Khamla";
                Sengphet = "Sengphet";
                Xay = "Xay";
                Chansy = "Chansy";
                Thongchai = "Thongchai";
                Vixay = "Vixay";
                Phoutthasone = "Phoutthasone";
                Douang = "Douang";
                Souvanny = "Souvanny";
                Khamphou = "Khamphou";
                Chanthone = "Chanthone";
                Sisouk = "Sisouk";
                Somsack = "Somsack";
                Phomma = "Phomma";
                Bounlue = "Bounlue";
                Khampheng = "Khampheng";
                Thonglith = "Thonglith";
                Vong = "Vong";
            };
            class LastNames
            {
                Sisavath = "Sisavath";
                Souvanthong = "Souvanthong";
                Inthavong = "Inthavong";
                Keomany = "Keomany";
                Sihavong = "Sihavong";
                Chansy = "Chansy";
                Phanthavong = "Phanthavong";
                Somphone = "Somphone";
                Bounmy = "Bounmy";
                Douangphouxay = "Douangphouxay";
                Xaysana = "Xaysana";
                Vongsavanh = "Vongsavanh";
                Phimmasone = "Phimmasone";
                Souvannavong = "Souvannavong";
                Khamphoumy = "Khamphoumy";
                Sengsouly = "Sengsouly";
                Thongsavath = "Thongsavath";
                Vannasith = "Vannasith";
                Phouangmala = "Phouangmala";
                Khamchai = "Khamchai";
                Vongphachanh = "Vongphachanh";
                Xayavong = "Xayavong";
                Thammavong = "Thammavong";
                Vannavong = "Vannavong";
                Douangchai = "Douangchai";
                Chanthavong = "Chanthavong";
                Souvannaseng = "Souvannaseng";
                Phanlasy = "Phanlasy";
                Thongsavanh = "Thongsavanh";
                Somsanith = "Somsanith";
                Khamvongsa = "Khamvongsa";
                Phommasane = "Phommasane";
                Inthasone = "Inthasone";
                Khamsouk = "Khamsouk";
                Vixay = "Vixay";
                Kongmany = "Kongmany";
                Chanthalangsy = "Chanthalangsy";
                Souvannaphong = "Souvannaphong";
                Bounnack = "Bounnack";
                Douangsavanh = "Douangsavanh";
                Xaybandith = "Xaybandith";
                Phengsavanh = "Phengsavanh";
                Sisouvanh = "Sisouvanh";
                Nanthavong = "Nanthavong";
                Vongxay = "Vongxay";
                Phommachanh = "Phommachanh";
                Soukthavong = "Soukthavong";
                Phouangpak = "Phouangpak";
                Somsavath = "Somsavath";
            };
        };
		class GermanMen
		{
			class FirstNames
			{
				Alexander = "Alexander";
				Andreas = "Andreas";
				Armin = "Armin";
				Bernhard = "Bernhard";
				Christian = "Christian";
				Dieter = "Dieter";
				Dirk = "Dirk";
				Erik = "Erik";
				Frank = "Frank";
				Fritz = "Fritz";
				Georg = "Georg";
				Gerd = "Gerd";
				Guenter = "Günter";
				Hans = "Hans";
				Harald = "Harald";
				Heinrich = "Heinrich";
				Helmut = "Helmut";
				Horst = "Horst";
				Juergen = "Jürgen";
				Karl = "Karl";
				Klaus = "Klaus";
				Lothar = "Lothar";
				Ludwig = "Ludwig";
				Manfred = "Manfred";
				Martin = "Martin";
				Norbert = "Norbert";
				Mark = "Mark";
				Rainer = "Rainer";
				Rolf = "Rolf";
				Uwe = "Uwe";
				Otto = "Otto";
				Wolfgang = "Wolfgang";
				Dietrich = "Dietrich";
				Hermann = "Hermann";
				Franz = "Franz";
				Richter = "Richter";
				Walter = "Walter";
				Albrecht = "Albrecht";
				Abel = "Abel";
			};
			class LastNames
			{
				Becker = "Becker";
				Bergmann = "Bergmann";
				Boehm = "Böhm";
				Braun = "Braun";
				Busch = "Busch";
				Ebert = "Ebert";
				Engel = "Engel";
				Ernst = "Ernst";
				Faber = "Faber";
				Fink = "Fink";
				Fischer = "Fischer";
				Franke = "Franke";
				Friedrich = "Friedrich";
				Graf = "Graf";
				Gross = "Groß";
				Guenther = "Günther";
				Hahn = "Hahn";
				Hartmann = "Hartmann";
				Heinemann = "Heinemann";
				Hoffmann = "Hoffmann";
				Horn = "Horn";
				Jaeger = "Jäger";
				Jung = "Jung";
				Kaiser = "Kaiser";
				Keller = "Keller";
				Koenig = "König";
				Kraemer = "Krämer";
				Krueger = "Krüger";
				Kuehn = "Kühn";
				Lange = "Lange";
				Lehmann = "Lehmann";
				Lorenz = "Lorenz";
				Maier = "Maier";
				Mertens = "Mertens";
				Meier = "Meier";
				Meyer = "Meyer";
				Moeller = "Möller";
				Mueller = "Müller";
				Neumann = "Neumann";
				Paulsen = "Paulsen";
				Peters = "Peters";
				Pohl = "Pohl";
				Reich = "Reich";
				Roth = "Roth";
				Schaefer = "Schäfer";
				Schmid = "Schmid";
				Schmidt = "Schmidt";
				Schneider = "Schneider";
				Scholz = "Scholz";
				Schulz = "Schulz";
				Schumacher = "Schumacher";
				Schuster = "Schuster";
				Schwarz = "Schwarz";
				Seidel = "Seidel";
				Sommer = "Sommer";
				Stahl = "Stahl";
				Stein = "Stein";
				Vogel = "Vogel";
				Wagner = "Wagner";
				Weber = "Weber";
				Weiss = "Weiß";
				Werner = "Werner";
				Ziegler = "Ziegler";
				Zimmermann = "Zimmermann";
				Feldmann = "Feldmann";
				Breuer = "Breuer";
				Funke = "Funke";
				Andresen = "Andresen";
				Barth = "Barth";
				Baumann = "Baumann";
				Berner = "Berner";
				Brandt = "Brandt";
				Drescher = "Drescher";
				Eisele = "Eisele";
				Fleischer = "Fleischer";
				Huebner = "Hübner";
				Koerner = "Körner";
				Lindner = "Lindner";
				Matthes = "Matthes";
				Nickel = "Nickel";
				Reuter = "Reuter";
				Roemer = "Römer";
				Stahlberg = "Stahlberg";
				Vetter = "Vetter";
				Zorn = "Zorn";
				Gruber = "Gruber";
			};
		};
    };
};
