// Logistics nodes for "Dingo 2 GE A3.2B (MG3)" (BWA3_Dingo2_FLW100_MG3_Fleck)
// Generated by ACNE, the Antistasi Cargo Nodes Editor
class bwa3_dingo2_bwa3_dingo2_flw100_mg3_p3d : TRIPLES(ADDON,Nodes,Base)
{
    class Nodes
    {
        class Node1
        {
            offset[] = {0,-2.079,1.397};
            seats[] = {};
        };
    };
};

// Logistics nodes for "Dingo 2 GE A3.4B CG-13 (MG3)" (BWA3_Dingo2_FLW100_MG3_CG13_Tropen)
// Generated by ACNE, the Antistasi Cargo Nodes Editor
class bwa3_dingo2_bwa3_dingo2_flw200_gmw_p3d : bwa3_dingo2_bwa3_dingo2_flw100_mg3_p3d {};

// Logistics nodes for "Dingo 2 GE A3.3 (M2)" (BWA3_Dingo2_FLW200_M2_Fleck)
// Generated by ACNE, the Antistasi Cargo Nodes Editor
class bwa3_dingo2_bwa3_dingo2_flw200_m2_p3d : bwa3_dingo2_bwa3_dingo2_flw100_mg3_p3d {};

// Logistics nodes for "IFV Puma" (BWA3_Puma_Fleck)
// Generated by ACNE, the Antistasi Cargo Nodes Editor
class bwa3_puma_bwa3_puma_p3d : TRIPLES(ADDON,Nodes,Base)
{
    class Nodes
    {
        class Node1
        {
            offset[] = {0,-3.168,1.92895};
            seats[] = {};
        };
    };
};

// Logistics nodes for "Eagle IV" (BWA3_Eagle_Fleck)
// Generated by ACNE, the Antistasi Cargo Nodes Editor
class bwa3_eagle_bwa3_eagle_p3d : TRIPLES(ADDON,Nodes,Base)
{
    class Nodes
    {
        class Node1
        {
            offset[] = {0,-2.203,1.123};
            seats[] = {};
        };

        class Node2
        {
            offset[] = {0,-2.203,1.539};
            seats[] = {};
        };
    };
};

// Logistics nodes for "MULTI A4 FSA" (BWA3_Multi_Fleck)
// Generated by ACNE, the Antistasi Cargo Nodes Editor
class bwa3_multi_bwa3_multi_p3d : TRIPLES(ADDON,Nodes,Base)
{
    class Nodes
    {
        class Node1
        {
            offset[] = {0,-0.28027,1.61};
            seats[] = {};
        };

        class Node2
        {
            offset[] = {0,-1.20033,1.61};
            seats[] = {};
        };

        class Node3
        {
            offset[] = {0,-2.12031,1.61};
            seats[] = {};
        };

        class Node4
        {
            offset[] = {0,-3.03966,1.61};
            seats[] = {};
        };

        class Node5
        {
            offset[] = {0,-3.95967,1.61};
            seats[] = {};
        };
    };
};

// Logistics nodes for "NH90 TTH" (BWA3_NH90_TTH_Fleck)
// Generated by ACNE, the Antistasi Cargo Nodes Editor
class bwa3_nh90_bwa3_nh90_p3d : TRIPLES(ADDON,Nodes,Base)
{
    class Nodes
    {
        class Node1
        {
            offset[] = {-0.550071,-2.55,1.0234};
            seats[] = {};
        };

        class Node2
        {
            offset[] = {0.550178,-2.55,1.0234};
            seats[] = {};
            canCouple = 0;
        };
    };
};
